### ISSUE TITLE
UPF performance issue for TCP traffic

### ISSUE THREAD

**Issue by thakurajayL** [omec-project/upf#644]
Multiple community members pointed out that TCP performance issue is seen with the TCP traffic. Wish we add enough details in this issue so that other community members can help in root causing the issue.

**Comment by thakurajayL** [comment]
RCA document is created in public folder. Please go through it and update your comments in the doc or in the GitHub issues. 
https://docs.google.com/document/d/1U9QvCU9C7QT-uHbl6-3yr1NKKv-PpYYRB2b-gORo_2k/edit

**Comment by infinitydon** [comment]
@thakurajayL - Did a test using UERANSIM and sd-core components, am getting more than 1Gbps using iperf3

```
ubuntu@ip-10-0-3-8:~$ sudo iperf3 -c 10.0.5.8 -B 172.250.237.121
Connecting to host 10.0.5.8, port 5201
[  5] local 172.250.237.121 port 37571 connected to 10.0.5.8 port 5201
[ ID] Interval           Transfer     Bitrate         Retr  Cwnd
[  5]   0.00-1.00   sec   156 MBytes  1.31 Gbits/sec  143    222 KBytes
[  5]   1.00-2.00   sec   156 MBytes  1.31 Gbits/sec   61    236 KBytes
[  5]   2.00-3.00   sec   134 MBytes  1.12 Gbits/sec   87    183 KBytes
[  5]   3.00-4.00   sec   155 MBytes  1.30 Gbits/sec   65    234 KBytes
[  5]   4.00-5.00   sec   168 MBytes  1.41 Gbits/sec   13    455 KBytes
[  5]   5.00-6.00   sec   172 MBytes  1.45 Gbits/sec  409    441 KBytes
[  5]   6.00-7.00   sec   190 MBytes  1.59 Gbits/sec   56    309 KBytes
[  5]   7.00-8.00   sec   190 MBytes  1.59 Gbits/sec   11    470 KBytes
[  5]   8.00-9.00   sec   159 MBytes  1.33 Gbits/sec  219    208 KBytes
[  5]   9.00-10.00  sec   119 MBytes   996 Mbits/sec   26    212 KBytes
- - - - - - - - - - - - - - - - - - - - - - - - -
[ ID] Interval           Transfer     Bitrate         Retr
[  5]   0.00-10.00  sec  1.56 GBytes  1.34 Gbits/sec  1090             sender
[  5]   0.00-10.00  sec  1.56 GBytes  1.34 Gbits/sec                  receiver

iperf Done.
```

Also confirmed that traffic is actually been processed via the bess-upf:

```
localhost:10514 $ tcpdump coreRoutes out 0
03:34:15.619719 IP cpe-172-250-237-121.socal.res.rr.com.37571 > ip-10-0-5-8.eu-central-1.compute.internal.5201: Flags [.], seq 687081029:687082377, ack 1, win 510, options [nop,nop,TS val 2058114087 ecr 705236662], length 1348
03:34:15.619719 IP cpe-172-250-237-121.socal.res.rr.com.37571 > ip-10-0-5-8.eu-central-1.compute.internal.5201: Flags [.], seq 687082377:687083725, ack 1, win 510, options [nop,nop,TS val 2058114087 ecr 705236662], length 1348
03:34:15.619719 IP cpe-172-250-237-121.socal.res.rr.com.37571 > ip-10-0-5-8.eu-central-1.compute.internal.5201: Flags [.], seq 687083725:687085073, ack 1, win 510, options [nop,nop,TS val 2058114087 ecr 705236662], length 1348
03:34:15.619719 IP cpe-172-250-237-121.socal.res.rr.com.37571 > ip-10-0-5-8.eu-central-1.compute.internal.5201: Flags [.], seq 687085073:687086421, ack 1, win 510, options [nop,nop,TS val 2058114087 ecr 705236662], length 1348
03:34:15.619719 IP cpe-172-250-237-121.socal.res.rr.com.37571 > ip-10-0-5-8.eu-central-1.compute.internal.5201: Flags [.], seq 687086421:687087769, ack 1, win 510, options [nop,nop,TS val 2058114087 ecr 705236662], length 1348
03:34:15.619719 IP cpe-172-250-237-121.socal.res.rr.com.37571 > ip-10-0-5-8.eu-central-1.compute.internal.5201: Flags [.], seq 687087769:687089117, ack 1, win 510, options [nop,nop,TS val 2058114087 ecr 705236662], length 1348
03:34:15.619719 IP cpe-172-250-237-121.socal.res.rr.com.37571 > ip-10-0-5-8.eu-central-1.compute.internal.5201: Flags [.], seq 687089117:687090465, ack 1, win 510, options [nop,nop,TS val 2058114087 ecr 705236662], length 1348
03:34:15.619719 IP cpe-172-250-237-121.socal.res.rr.com.37571 > ip-10-0-5-8.eu-central-1.compute.internal.5201: Flags [.], seq 687090465:687091813, ack 1, win 510, options [nop,nop,TS val 2058114087 ecr 705236662], length 1348
03:34:15.619719 IP cpe-172-250-237-121.socal.res.rr.com.37571 > ip-10-0-5-8.eu-central-1.compute.internal.5201: Flags [.], seq 687091813:687093161, ack 1, win 510, options [nop,nop,TS val 2058114087 ecr 705236662], length 1348
```

What values are others getting using iperf3?

**Comment by infinitydon** [comment]
Curl file download and speedtest results:

```
ubuntu@ip-10-0-3-8:~$ curl --interface uesimtun0 https://speed.hetzner.de/1GB.bin --output 1GB.bin
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100 1000M  100 1000M    0     0  28.0M      0  0:00:35  0:00:35 --:--:-- 21.7M
ubuntu@ip-10-0-3-8:~$
ubuntu@ip-10-0-3-8:~$
ubuntu@ip-10-0-3-8:~$ curl --interface uesimtun0 https://speed.hetzner.de/10GB.bin --output 10GB.bin
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  9.7G  100  9.7G    0     0  27.5M      0  0:06:03  0:06:03 --:--:-- 27.3M
```

```
ubuntu@ip-10-0-3-8:~/ueransim-master/build$ speedtest-cli --source 172.250.237.121
Retrieving speedtest.net configuration...
Testing from Amazon.com (3.65.220.104)...
Retrieving speedtest.net server list...
Selecting best server based on ping...
Hosted by Scaleway (Vitry-sur-Seine) [478.09 km]: 11.63 ms
Testing download speed................................................................................
Download: 343.10 Mbit/s
Testing upload speed......................................................................................................
Upload: 397.42 Mbit/s
```

**Comment by cmaciocco** [comment]
We've identified random packets drop which would impact TCP flows. Suresh has root caused the issue and worked on a resolution

**Comment by fefer** [comment]
Is there a helm chart for it? Or just source code? Maybe a container image we can point to get this new version?

**Comment by amarsri28** [comment]
just measure with     "measure_flow": false,    to avoid packet loss issue in upf.json

**Comment by infinitydon** [comment]
@fefer - I am using iperf3.

Did another test using your command:

```
ubuntu@ip-10-0-3-8:~$ sudo iperf3 -c 10.0.5.8 -B 172.250.237.121 -R
Connecting to host 10.0.5.8, port 5201
Reverse mode, remote host 10.0.5.8 is sending
[  5] local 172.250.237.121 port 39447 connected to 10.0.5.8 port 5201
[ ID] Interval           Transfer     Bitrate
[  5]   0.00-1.00   sec   121 MBytes  1.01 Gbits/sec
[  5]   1.00-2.00   sec   119 MBytes   999 Mbits/sec
[  5]   2.00-3.00   sec   110 MBytes   923 Mbits/sec
[  5]   3.00-4.00   sec   101 MBytes   850 Mbits/sec
[  5]   4.00-5.00   sec  95.8 MBytes   803 Mbits/sec
[  5]   5.00-6.00   sec   103 MBytes   867 Mbits/sec
[  5]   6.00-7.00   sec   115 MBytes   961 Mbits/sec
[  5]   7.00-8.00   sec   113 MBytes   946 Mbits/sec
[  5]   8.00-9.00   sec   111 MBytes   934 Mbits/sec
[  5]   9.00-10.00  sec   108 MBytes   910 Mbits/sec
- - - - - - - - - - - - - - - - - - - - - - - - -
[ ID] Interval           Transfer     Bitrate         Retr
[  5]   0.00-10.00  sec  1.07 GBytes   921 Mbits/sec  1408             sender
[  5]   0.00-10.00  sec  1.07 GBytes   920 Mbits/sec                  receiver

iperf Done.
```

**Comment by sureshmarikkannu** [comment]
We observed packet drops when we enable "measure_upf": true in  conf/upf.json. If this enabled then two modules are added to the pipeline namely timestamp and measure which is used to calculate latency/jitter. The way measure module process the packets impacts the fastpath packet processing. I am working on an alternate approach to improve this hurdle. Please disable above parameter to avoid packet drops. let us know if it helps in resolving your issue.

**Comment by sureshmarikkannu** [comment]
> just measure with "measure_flow": false, to avoid packet loss issue in upf.json

Its "measure_upf" parameters which causes the drops. Please disable it and try.

**Comment by thakurajayL** [comment]
If aiab is used for tests then please do following changes,

aether-in-a-box/sd-core-5g-values.yaml


@@ -256,11 +258,12 @@ omec-user-plane:
           hwcksum: true
           log_level: "trace"
           gtppsc: true #extension header is enabled in 5G. Sending QFI in pdu session extension header
+          measure_upf: false
           cpiface:
             dnn: "internet" #keep it matching with Slice dnn
             hostname: "upf"
             #http_port: "8080"

**Comment by thakurajayL** [comment]
@infinitydon I assume you are not changing default measure_upf value. By default measure upf is set to true. Do you use Kubernetes deployment ? Thanks for your help !

**Comment by infinitydon** [comment]
@thakurajayL This is running in k8s, measure_upf is set to false, below is my upf.json

```
{
  "access": {
    "ifname": "access"
  },
  "core": {
    "ifname": "core"
  },
  "cpiface": {
    "dnn": "internet",
    "enable_ue_ip_alloc": false,
    "hostname": "upf",
    "http_port": "8080"
  },
  "enable_notify_bess": false,
  "log_level": "trace",
  "max_sessions": 50000,
  "measure_flow": false,
  "measure_upf": false,
  "mode": "dpdk",
  "notify_sockaddr": "/pod-share/notifycp",
  "qci_qos_config": [
    {
      "burst_duration_ms": 10,
      "cbs": 50000,
      "ebs": 50000,
      "pbs": 50000,
      "priority": 7,
      "qci": 0
    }
  ],
  "slice_rate_limit_config": {
    "n3_bps": 10000000000,
    "n3_burst_bytes": 125000000,
    "n6_bps": 10000000000,
    "n6_burst_bytes": 125000000
  },
  "table_sizes": {
    "appQERLookup": 200000,
    "farLookup": 150000,
    "pdrLookup": 50000,
    "sessionQERLookup": 100000
  },
  "workers": 4
}
```

Also not sure if it will, in simapp I set the MBR to 4Gpbs:

```
config:
  simapp:
    cfgFiles:
      simapp.yaml:
        configuration:
          provision-network-slice: true
          sub-provision-endpt:
            addr: webui
            port: 5000
          subscribers:
          - ueId-start: "208934567891201"
            ueId-end: "208934567891205"
            plmnId: 20893
            opc: "d4416644f6154936193433dd20a0ace0"
            op: ""
            key: "465b5ce8b199b49faa5f0a2ee238a6bc"
            sequenceNumber: 96
          device-groups:
          - name:  "5g-oaisim-user"
            imsis:
              - "208934567891201"
              - "208934567891202"
              - "208934567891203"
              - "208934567891204"
              - "208934567891205"
            ip-domain-name: "pool1"
            ip-domain-expanded:
              dnn: internet
              dns-primary: "8.8.8.8"
              mtu: 1460
              ue-ip-pool: "172.250.0.0/16"
              ue-dnn-qos:
                dnn-mbr-downlink: 4000000000
                dnn-mbr-uplink: 4000000000
                bitrate-unit: bps
                traffic-class:  #default bearer QCI/ARP
                  name: "platinum"
                  qci: 9
                  arp: 1
                  pdb: 300
                  pelr: 6
            site-info: "aiab"
          network-slices:
          - name: "default"
            slice-id:
              sd: "010203"
              sst: 1
            site-device-group:
            - "5g-oaisim-user"
            site-info:
              gNodeBs:
              - name: "ueransim-gnb1"
                tac: 1
              plmn:
                mcc: "208"
                mnc: "93"
              site-name: "aiab"
              upf:
                upf-name: "upf"
                upf-port: 8805
```

From my experience if the AMF is passing the MBR value to UERANSIM, UERANSIM will honor that and throttle the throughput, so this aspect can be checked also.

I will try to test with the upf_measure set to true
